[package]
name = "assign7"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]

[dependencies]
time = "0.1"
clap = "2.27.1"
serde = "1.0.19"
serde_json = "1.0.6"
num_cpus = "1.0"
lazy_static = "0.2"